TAK <- read.csv("~/IdeaProjects/tak-ai/rec/TakAIRecords-0.csv", fileEncoding="UTF-16")
table(TAK$winner)
barplot(table(TAK$winner))
plot(table(TAK$winner, TAK$p1))
scatter.smooth(tail(TAK$score, 4000))
scatter.smooth(tail(TAK$numTurns, 4000))
scatter.smooth(tail(TAK$score, nrow(TAK)), type="n", ylab="Score", main="Score Over Time")
scatter.smooth(tail(TAK$numTurns, nrow(TAK)), ylab="Number of Turns", main="Number of Turns over Time")
scatter.smooth(tail(TAK$timeElapsed, nrow(TAK)))
# plot(TAK$numTurns ~ TAK$score, ylab="Number of Turns", xlab="Score", main="Relationship of Score and Number of Turns")
hist(tail(TAK$numTurns, nrow(TAK)), breaks = 100)

WEIGHTS <- read.csv("~/IdeaProjects/tak-ai/weight-cache/TakAIWeights-0.csv", fileEncoding="UTF-16")
weights <- read.csv("~/IdeaProjects/tak-ai/weight-cache/TakAIWeights-0.csv", fileEncoding="UTF-16")
hist(as.numeric(weights[nrow(weights),]), breaks=10, xlab="Value of Individual Weights", main="Distribution of Weight Values after 25000 games")
scatter.smooth(as.numeric(weights[nrow(weights),]), ylab = "Value of Individual Weights", main="Scatterplot Distribution of Weights after 25000 games")

weights <- subset(WEIGHTS[2:ncol(WEIGHTS)])
hist(as.numeric(weights[nrow(weights),]))
scatter.smooth(as.numeric(weights[nrow(weights),]))
